### PR TITLE
macOS Icon Design Fix

### PR DESCRIPTION
**Pull request by TheMasterOfTech**
Current macOS icon does not meet Apple Design Standards and is not consistent across the operating system design scheme. This pull request is aimed at resolving those issues.

### CODE REVIEW

**Comment by TheMasterOfTech** [comment]
I am unsure how to squash commits via the web browser. If I have to do it through the client side (which from what I see I have to), that can be done later.

**Comment by spuder** [comment]
Great. There is 1 file that still shouldn't be here: `AnkerSlicer/distrib/AnkerMake.icns`

**Comment by spuder** [comment]
For squashing, you can do it with the github app https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/managing-commits/squashing-commits

**Comment by dzienisz** [comment]
I see in todays version that it's fixed! I wonder why this PR is not merged or closed hmm!

Screenshot 2023-03-29 at 09 47 05

**Comment by spuder** [comment]
I think AnkerSlicer/distrib/AnkerMake.icns should probably be removed. 

This PR may not be required if Anker already fixed it. Sometimes they don't push updates right away.

**Comment by dzienisz** [comment]
I think this is already fixed

**Pull request closed without merging**
